"""initial stateful email workflow schema

Revision ID: 13d76d83d129
Revises:
Create Date: 2026-07-18 22:03:40.368086
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "13d76d83d129"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("root_message_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_subject", sa.String(length=500), nullable=False),
        sa.Column("primary_sender", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_table(
        "mail_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("mailbox", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_uidvalidity", sa.Integer(), nullable=True),
        sa.Column("polling_checkpoint", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_accounts")),
        sa.UniqueConstraint("name", name=op.f("uq_mail_accounts_name")),
    )
    op.create_table(
        "email_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mail_account_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("rfc_message_id", sa.String(length=998), nullable=True),
        sa.Column("normalized_message_id", sa.String(length=998), nullable=True),
        sa.Column("in_reply_to", sa.String(length=998), nullable=True),
        sa.Column("references_json", sa.JSON(), nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("reply_to", sa.String(length=500), nullable=True),
        sa.Column("recipients_json", sa.JSON(), nullable=False),
        sa.Column("cc_json", sa.JSON(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("normalized_subject", sa.String(length=500), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("latest_user_message", sa.Text(), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("signature_text", sa.Text(), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("raw_eml_path", sa.Text(), nullable=True),
        sa.Column("raw_eml_blob", sa.LargeBinary(), nullable=True),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=200), nullable=True),
        sa.Column("attachment_metadata", sa.JSON(), nullable=False),
        sa.Column("imap_uid", sa.Integer(), nullable=True),
        sa.Column("uidvalidity", sa.Integer(), nullable=True),
        sa.Column("mailbox_name", sa.String(length=200), nullable=True),
        sa.Column("flags_json", sa.JSON(), nullable=False),
        sa.Column("internal_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_status", sa.String(length=30), nullable=False),
        sa.Column("duplicate_of_id", sa.Uuid(), nullable=True),
        sa.Column("automated_classification", sa.String(length=100), nullable=True),
        sa.Column("parsing_warnings", sa.JSON(), nullable=False),
        sa.Column("authorization_allowed", sa.Boolean(), nullable=True),
        sa.Column("authorization_reason", sa.Text(), nullable=True),
        sa.Column("correlation_details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_email_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["email_messages.id"],
            name=op.f("fk_email_messages_duplicate_of_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["mail_account_id"],
            ["mail_accounts.id"],
            name=op.f("fk_email_messages_mail_account_id_mail_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_messages")),
        sa.UniqueConstraint(
            "mail_account_id",
            "mailbox_name",
            "uidvalidity",
            "imap_uid",
            name="uq_email_physical_mailbox_locator",
        ),
    )
    op.create_index(
        op.f("ix_email_messages_conversation_id"),
        "email_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_in_reply_to"), "email_messages", ["in_reply_to"], unique=False
    )
    op.create_index(
        op.f("ix_email_messages_mail_account_id"),
        "email_messages",
        ["mail_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_normalized_message_id"),
        "email_messages",
        ["normalized_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_normalized_subject"),
        "email_messages",
        ["normalized_subject"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_processing_status"),
        "email_messages",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_raw_sha256"), "email_messages", ["raw_sha256"], unique=False
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("public_reference", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("initiating_email_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("request_kind", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_completion_marker", sa.String(length=100), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("human_assignment", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_requests_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["initiating_email_id"],
            ["email_messages.id"],
            name=op.f("fk_requests_initiating_email_id_email_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    op.create_index(
        op.f("ix_requests_conversation_id"), "requests", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_requests_public_reference"), "requests", ["public_reference"], unique=True
    )
    op.create_index(op.f("ix_requests_status"), "requests", ["status"], unique=False)
    op.create_table(
        "clarifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("outbound_email_id", sa.Uuid(), nullable=True),
        sa.Column("source_inbound_email_id", sa.Uuid(), nullable=False),
        sa.Column("target_operation_ids", sa.JSON(), nullable=False),
        sa.Column("requested_fields", sa.JSON(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reply_email_id", sa.Uuid(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["outbound_email_id"],
            ["email_messages.id"],
            name=op.f("fk_clarifications_outbound_email_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["reply_email_id"],
            ["email_messages.id"],
            name=op.f("fk_clarifications_reply_email_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], name=op.f("fk_clarifications_request_id_requests")
        ),
        sa.ForeignKeyConstraint(
            ["source_inbound_email_id"],
            ["email_messages.id"],
            name=op.f("fk_clarifications_source_inbound_email_id_email_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clarifications")),
    )
    op.create_index(
        op.f("ix_clarifications_request_id"), "clarifications", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_clarifications_status"), "clarifications", ["status"], unique=False)
    op.create_table(
        "escalations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("email_message_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_message_id"],
            ["email_messages.id"],
            name=op.f("fk_escalations_email_message_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], name=op.f("fk_escalations_request_id_requests")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalations")),
    )
    op.create_index(
        op.f("ix_escalations_reason_code"), "escalations", ["reason_code"], unique=False
    )
    op.create_index(op.f("ix_escalations_request_id"), "escalations", ["request_id"], unique=False)
    op.create_table(
        "operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("pdv_code", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("additional_payload", sa.JSON(), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("field_provenance", sa.JSON(), nullable=False),
        sa.Column("analyzer_confidence", sa.JSON(), nullable=False),
        sa.Column("verifier_confidence", sa.JSON(), nullable=False),
        sa.Column("contradiction_data", sa.JSON(), nullable=False),
        sa.Column("model_agreement", sa.Boolean(), nullable=True),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("execution_eligible", sa.Boolean(), nullable=False),
        sa.Column("final_decision", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], name=op.f("fk_operations_request_id_requests")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("request_id", "sequence_number", name="uq_operation_request_sequence"),
    )
    op.create_index(op.f("ix_operations_action"), "operations", ["action"], unique=False)
    op.create_index(op.f("ix_operations_request_id"), "operations", ["request_id"], unique=False)
    op.create_index(op.f("ix_operations_status"), "operations", ["status"], unique=False)
    op.create_table(
        "executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("operation_revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_executions_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    op.create_index(
        op.f("ix_executions_idempotency_key"), "executions", ["idempotency_key"], unique=True
    )
    op.create_index(
        op.f("ix_executions_operation_id"), "executions", ["operation_id"], unique=False
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email_message_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("backend", sa.String(length=100), nullable=False),
        sa.Column("model_family", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=300), nullable=False),
        sa.Column("quantization", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("input_context_hash", sa.String(length=64), nullable=False),
        sa.Column("input_context", sa.JSON(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("parsed_output", sa.JSON(), nullable=False),
        sa.Column("structured_output_valid", sa.Boolean(), nullable=False),
        sa.Column("latency_seconds", sa.Float(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("logprobs", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_message_id"],
            ["email_messages.id"],
            name=op.f("fk_model_runs_email_message_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_model_runs_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_index(
        op.f("ix_model_runs_email_message_id"), "model_runs", ["email_message_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_runs_input_context_hash"), "model_runs", ["input_context_hash"], unique=False
    )
    op.create_index(
        op.f("ix_model_runs_operation_id"), "model_runs", ["operation_id"], unique=False
    )
    op.create_index(op.f("ix_model_runs_stage"), "model_runs", ["stage"], unique=False)
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("related_request_id", sa.Uuid(), nullable=True),
        sa.Column("related_clarification_id", sa.Uuid(), nullable=True),
        sa.Column("outbound_email_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["outbound_email_id"],
            ["email_messages.id"],
            name=op.f("fk_outbox_messages_outbound_email_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["related_clarification_id"],
            ["clarifications.id"],
            name=op.f("fk_outbox_messages_related_clarification_id_clarifications"),
        ),
        sa.ForeignKeyConstraint(
            ["related_request_id"],
            ["requests.id"],
            name=op.f("fk_outbox_messages_related_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("outbound_email_id", name=op.f("uq_outbox_messages_outbound_email_id")),
    )
    op.create_index(
        op.f("ix_outbox_messages_related_request_id"),
        "outbox_messages",
        ["related_request_id"],
        unique=False,
    )
    op.create_index(op.f("ix_outbox_messages_status"), "outbox_messages", ["status"], unique=False)
    op.create_table(
        "validation_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("analyzer_result", sa.JSON(), nullable=False),
        sa.Column("verifier_result", sa.JSON(), nullable=False),
        sa.Column("hard_invariant_results", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_validation_decisions_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_decisions")),
    )
    op.create_index(
        op.f("ix_validation_decisions_decision"), "validation_decisions", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_validation_decisions_operation_id"),
        "validation_decisions",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "field_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("source_email_id", sa.Uuid(), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
            name=op.f("fk_field_revisions_model_run_id_model_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_field_revisions_operation_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["source_email_id"],
            ["email_messages.id"],
            name=op.f("fk_field_revisions_source_email_id_email_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_revisions")),
    )
    op.create_index(
        op.f("ix_field_revisions_operation_id"), "field_revisions", ["operation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_field_revisions_operation_id"), table_name="field_revisions")
    op.drop_table("field_revisions")
    op.drop_index(op.f("ix_validation_decisions_operation_id"), table_name="validation_decisions")
    op.drop_index(op.f("ix_validation_decisions_decision"), table_name="validation_decisions")
    op.drop_table("validation_decisions")
    op.drop_index(op.f("ix_outbox_messages_status"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_related_request_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_model_runs_stage"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_operation_id"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_input_context_hash"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_email_message_id"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_executions_operation_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_idempotency_key"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_operations_status"), table_name="operations")
    op.drop_index(op.f("ix_operations_request_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_action"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_escalations_request_id"), table_name="escalations")
    op.drop_index(op.f("ix_escalations_reason_code"), table_name="escalations")
    op.drop_table("escalations")
    op.drop_index(op.f("ix_clarifications_status"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_request_id"), table_name="clarifications")
    op.drop_table("clarifications")
    op.drop_index(op.f("ix_requests_status"), table_name="requests")
    op.drop_index(op.f("ix_requests_public_reference"), table_name="requests")
    op.drop_index(op.f("ix_requests_conversation_id"), table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_email_messages_raw_sha256"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_processing_status"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_normalized_subject"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_normalized_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_mail_account_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_in_reply_to"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_conversation_id"), table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_table("mail_accounts")
    op.drop_table("conversations")
    # ### end Alembic commands ###
